- name: Install redis component
  hosts: redis
  become: yes
  tasks:
  - name: Install redis repo
    ansible.builtin.commnd:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: installed
  
  # - name: Enable redis 6.2
  #   ansible.builin.command: yum module enable redis:remi-6.2 -y
      
    