- name: Install redis component
  hosts: redis
  become: yes
  tasks:
  - name: Install redis repo
    ansible.builtin.yum_repository:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: installed
      disable_gpg_check: true
  
  - name: Enable Redis 8.1
    ansible.builtin.command: yum module enable redis:remi-6.2  
  - name: Install redis
    ansible.builtin.yum:
     nem: redis
     state: installed  
  - name: allow remote locations to redis
    ansible.builtin.replace:
     path: /etc/redis.conf
     regexp: 127.0.0.1
     replace: 0.0.0.0
  - name: start ans enable redis
    ansible.builtin.service:
     name: redis
     state: started
     ebnabled: true